# -*- coding: utf-8 -*-
"""DS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFxar94K2O_zrDI2y0Ho4rnpznrZssyK
"""

# forecasting - predicting something WRT time using the past and present data

# forcasting-  the vegetable prices
# dataset -

import pandas as pd
df = pd.read_html('/content/DailyWiseMarketArrivals.html')[-1]
df

type(df)

df.shape

df.size

df.info()

# to check the null values
df.isnull().sum()

#now let us drop the null values
df = df.dropna()

df.isnull().sum()

#FB PROPHET- it only take data in form of 2 columns - ds and y - compulsory names
#then we should consider Data and Modal price
# rename data - ds and model price -y
df = df.rename(columns = {'Date':'ds','Modal Price (Rs/q)':'y'})
df

# LET US create a new dataframe and consider only 2 columns ds and y from old dataframe
df1 = df[['ds','y']]
df1

df1.info()

# the database od the ds column is in object object/string format. convert into datatime format
#the datatype of y column is in the object/string format.convert it in to integer format
df1['ds'] = pd.to_datetime(df1['ds'])
df1['y'] = df1['y'].astype(int)

#visualisation
import matplotlib.pyplot as plt
plt.figure(figsize=(25,5))
plt.scatter(df1['ds'],df1['y'])
plt.show()

#fb prophet
import prophet
op = prophet.Prophet()

op.fit(df1) # plotting the values of df1 in fbprophet library

forecast = op.make_future_dataframe(periods=365, freq = 'D')
forecast = op.predict(forecast)

op.plot(forecast,xlabel = 'Date', ylabel = 'Potato Price/q')
#the black dots are the original price
# the light blue shade is minimum and maximum price of potato as predicted by the model
#dark blue line is the best fit line

